In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier

In [2]:
data = pd.read_csv('train_test.csv')

In [6]:
data.head()

,firstname_lastname_1,firstname_lastname_3,firstname_lastname_7,ssn_dob_30,ssn_homephone_30,firstname_lastname_30,firstname_lastname_15,firstname_lastname_dob_15,ssn_15,ssn_homephone_15,...,ssn_30,address_7,ssn_7,homephone_zip5_7,address_zip5_7,homephone_zip5_30,firstname_lastname_homephone_30,firstname_lastname_zip5_15,address_30,fraud
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
2,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0

In [7]:
data.describe()

,firstname_lastname_1,firstname_lastname_3,firstname_lastname_7,ssn_dob_30,ssn_homephone_30,firstname_lastname_30,firstname_lastname_15,firstname_lastname_dob_15,ssn_15,ssn_homephone_15,...,ssn_30,address_7,ssn_7,homephone_zip5_7,address_zip5_7,homephone_zip5_30,firstname_lastname_homephone_30,firstname_lastname_zip5_15,address_30,fraud
count,77850.000000,77850.000000,77850.000000,77850.000000,77850.000000,77850.000000,77850.000000,77850.000000,77850.000000,77850.000000,...,77850.000000,77850.000000,77850.000000,77850.000000,77850.000000,77850.000000,77850.000000,77850.000000,77850.000000,77850.000000
mean,1.060809,1.081053,1.109621,1.218613,1.077996,1.210597,1.144265,1.027296,1.029107,1.047258,...,1.040604,1.020501,1.022453,1.020604,1.020501,1.035735,1.034310,1.024933,1.034644,0.203288
std,0.249243,0.314510,0.442952,2.283395,0.923408,0.970650,0.622064,0.181375,0.233982,0.489601,...,0.332885,0.149471,0.175901,0.149027,0.149471,0.225783,0.223058,0.172876,0.228075,0.402448
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
50%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,4.000000,6.000000,9.000000,45.000000,26.000000,21.000000,13.000000,7.000000,10.000000,16.000000,...,16.000000,5.000000,7.000000,5.000000,5.000000,10.000000,10.000000,7.000000,10.000000,1.000000

In [3]:
labels = data['fraud']
features = data.iloc[:,:25]
features.head()
##split the label and the feature

,firstname_lastname_1,firstname_lastname_3,ssn_homephone_30,zip5_15,zip5_30,ssn_homephone_15,firstname_lastname_30,ssn_7,ssn_15,ssn_dob_30,...,address_zip5_30,ssn_zip5_30,homephone_zip5_30,address_zip5_7,address_7,ssn_zip5_15,address_15,firstname_lastname_zip5_15,firstname_lastname_zip5_7,firstname_lastname_homephone_30
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [19]:
from sklearn.cross_validation import train_test_split
x_train, x_test,y_train,y_test = train_test_split(features, labels,test_size = 0.2, random_state = 0)
print(sum(y_train)) #fraud rate of training data
print(sum(y_test)) #fraud rate of testing data

12669
3157

### Random Forest Model

In [11]:
rf_clf = RandomForestClassifier(max_depth=15,n_estimators=50, min_samples_leaf=50,
                                  min_samples_split=100, random_state=0)
rf_clf.fit(x_train,y_train)
imp_feat_rf = pd.Series(rf_clf.feature_importances_, index=x_train.columns).sort_values(ascending=False)

print(len(imp_feat_rf))
imp_feat_rf

25

firstname_lastname_3               0.203531
firstname_lastname_1               0.190742
firstname_lastname_7               0.162536
firstname_lastname_15              0.145899
firstname_lastname_30              0.066139
ssn_7                              0.042209
firstname_lastname_dob_15          0.032349
ssn_dob_30                         0.030821
ssn_dob_15                         0.022381
ssn_30                             0.013230
address_7                          0.012022
ssn_dob_7                          0.010712
firstname_lastname_zip5_15         0.010220
homephone_zip5_7                   0.009024
firstname_lastname_dob_7           0.008964
ssn_homephone_30                   0.007538
ssn_15                             0.006745
firstname_lastname_homephone_30    0.006535
address_30                         0.004981
ssn_homephone_15                   0.003536
homephone_zip5_30                  0.003441
address_zip5_7                     0.002642
address_zip5_15                    0.001914
address_15                         0.001610
homephone_zip5_15                  0.000281
dtype: float64

Above is the feature importance extent by descending order

In [38]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score

def test_result(clf):
    rf_clf.fit(x_train, y_train)
    prediction_train = rf_clf.predict(x_train)
    matrix = confusion_matrix(y_train, prediction_train)
    train_acc = rf_clf.score(x_train, y_train)
    train_auc = roc_auc_score(y_train, prediction_train)
    train_fdr = matrix[1,1]/sum(y_train)

    prediction_test = rf_clf.predict(x_test)
    matrix = confusion_matrix(y_test, prediction_test)
    test_acc = rf_clf.score(x_test, y_test)
    test_auc = roc_auc_score(y_test, prediction_test)
    test_fdr = matrix[1,1]/sum(y_test)

    comparison_df = pd.DataFrame({ "Accuracy": [train_acc, test_acc],
                                  "AUC score": [train_auc, test_auc],
                                  "FDR": [train_fdr, test_fdr]},
                                 index = ["Training", "Testing"])
    return comparison_df
    

test_result(rf_clf)

          AUC score  Accuracy       FDR
Training   0.541831  0.809522  0.090536
Testing    0.536487  0.807964  0.079823

In [9]:
rf_clf = RandomForestClassifier(max_depth=15,n_estimators=50, min_samples_leaf=50,
                                  min_samples_split=100, random_state=0)

In [170]:
int(train_pred.shape[0]*i)

622

In [21]:
rf_clf.fit(x_train, y_train)
train1 = rf_clf.predict_proba(x_train)
train1 = pd.DataFrame(train1)

train_pred = pd.concat([y_train.reset_index(drop = True), train1],axis =1)
train_pred = train_pred.sort_values(1, ascending = False)

train_pred.shape

output_train = []
for i in range(1,11):
    i = i/10
    train_pred_per = train_pred.head(int(train_pred.shape[0]*0.1))
    train_count1 = train_pred_per['fraud'].value_counts()[1]
    fdr = train_count1/sum(train_pred['fraud'])
    output_train.append(fdr)
    
output_train

[0.18920198910726971,
 0.18920198910726971,
 0.18920198910726971,
 0.18920198910726971,
 0.18920198910726971,
 0.18920198910726971,
 0.18920198910726971,
 0.18920198910726971,
 0.18920198910726971,
 0.18920198910726971]

In [134]:
train_count1/sum(train_pred['fraud'])

0.22653721682847897

In [147]:
train_pred_per = train_pred.head(int(train_pred.shape[0]*0.1))
train_count1 = train_pred_per['fraud'].value_counts()[1]
train_count1
#fdr = train_count1/sum(train_pred['fraud'])
#fdr

2870

In [11]:
test1 = rf_clf.predict_proba(x_test)
test1 = pd.DataFrame(test1)
test_pred = pd.concat([y_test.reset_index(drop = True), test1],axis =1)
test_pred = test_pred.sort_values(1, ascending = False)

output_test = []
for i in range(1,11):
    i = i/10
    test_pred_per = test_pred.head(int(test_pred.shape[0]*i))
    test_count1 = test_pred_per['fraud'].value_counts()[1]
    fdr = test_count1/sum(test_pred['fraud'])
    output_test.append(fdr)
    
output_test

[0.18213493823249921,
 0.27272727272727271,
 0.36680392777953752,
 0.46404814697497626,
 0.55875831485587579,
 0.64459930313588854,
 0.74121000950269245,
 0.82926829268292679,
 0.91574279379157431,
 1.0]

In [138]:
703/sum(test_pred['fraud'])

0.22267975926512512

### Adjusting

In [36]:
# Define a new Random Forest Classifier
from sklearn.grid_search import GridSearchCV
select_rf_clf = RandomForestClassifier(random_state=10)

param_grid = {
    
            'n_estimators': [50, 80, 100],
            'max_depth': [5,10, 15]
}

# we will 10-fold cross-validation
grid_clf = GridSearchCV(select_rf_clf,param_grid,cv=10)
grid_clf.fit(x_train,y_train)

# Take the best model
best_rf_clf = grid_clf.best_estimator_
predicted_proba = best_rf_clf.predict_proba(x_test)
predicted_proba

array([[ 0.82417356,  0.17582644],
       [ 0.82417356,  0.17582644],
       [ 0.82417356,  0.17582644],
       ...,
       [ 0.82417356,  0.17582644],
       [ 0.82417356,  0.17582644],
       [ 0.82417356,  0.17582644]])

In [16]:
### adjust manually
rf_clf1 = RandomForestClassifier(max_depth=10,n_estimators=50, 
                                  min_samples_split=2, random_state=10, n_jobs =1)
test_result(rf_clf1)

          AUC score  Accuracy       FDR
Training   0.541831  0.809522  0.090536
Testing    0.536487  0.807964  0.079823

In [5]:
OOD = pd.read_csv('out_of_date.csv')
OOD.head()
print(sum(OOD['fraud']))

4338

In [3]:
ood_label = OOD['fraud']
ood_features = OOD.iloc[:,:25]
rf_clf.fit(ood_features,ood_label)
prediction_ood = rf_clf.predict(ood_features)
print("FDR of ood is:",sum(prediction_ood)/sum(ood_label)*100,"%")

NameError: name 'rf_clf' is not defined

In [15]:
ood1 = rf_clf.predict_proba(ood_features)
ood1 = pd.DataFrame(ood1)
ood_pred = pd.concat([ood_label.reset_index(drop = True), ood1],axis =1)
ood_pred = ood_pred.sort_values(1, ascending = False)

output_ood = []
for i in range(1,11):
    i = i/10
    ood_pred_per = ood_pred.head(int(ood_pred.shape[0]*i))
    ood_count1 = ood_pred_per['fraud'].value_counts()[1]
    fdr = ood_count1/sum(ood_pred['fraud'])
    output_ood.append(fdr)
    
output_ood

[0.1615952051636699,
 0.26071922544951592,
 0.35431074227754727,
 0.44905486399262334,
 0.54310742277547253,
 0.63439372982941444,
 0.72153065928999538,
 0.8144306131857999,
 0.91470723835869061,
 1.0]

In [140]:
720/sum(ood_pred['fraud'])

0.16597510373443983